# **numpy.concatenate() in Python**
The concatenate() function is a function from the NumPy package. This function essentially combines NumPy arrays together. This function is basically used for joining two or more arrays of the same shape along a specified axis. There are the following things which are essential to keep in mind:

NumPy's concatenate() is not like a traditional database join. It is like stacking NumPy arrays.
This function can operate both vertically and horizontally. This means we can concatenate arrays together horizontally or vertically.
numpy.concatenate()
The concatenate() function is usually written as np.concatenate(), but we can also write it as numpy.concatenate(). It depends on the way of importing the numpy package, either import numpy as np or import numpy, respectively.

In [1]:
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y))  
z  

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [2]:
#numpy.concatenate() with axis=0
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=0)  
z  

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [3]:
#numpy.concatenate() with axis=1
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y.T), axis=1)  
z  

array([[ 1,  2, 12],
       [ 3,  4, 30]])

In [5]:
#numpy.concatenate() with axis=None
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=None)  
z  

array([ 1,  2,  3,  4, 12, 30])

# **numpy.append() in Python**
The numpy.append() function is available in NumPy package. As the name suggests, append means adding something. The numpy.append() function is used to add or append new values to an existing numpy array. This function adds the new values at the end of the array.

The numpy append() function is used to merge two arrays. It returns a new array, and the original array remains unchanged.

In [7]:
# np.append()
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
c 

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

In [8]:
#np.append({a1,a2,...}, axis=0)
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=0)  
c  

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [9]:
#np.append({a1,a2,...}, axis=1)
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=1)  
c  

array([[10, 20, 30, 11, 21, 31],
       [40, 50, 60, 42, 52, 62],
       [70, 80, 90, 73, 83, 93]])

# **numpy.sum() in Python**
The numpy.sum() function is available in the NumPy package of Python. This function is used to compute the sum of all elements, the sum of each row, and the sum of each column of a given array.
Essentially, this sum ups the elements of an array, takes the elements within a ndarray, and adds them together. It is also possible to add rows and column elements of an array.
The output will be in the form of an array object

![image](https://user-images.githubusercontent.com/84801896/123977559-b6edc380-d9dc-11eb-8b72-cf25468012b4.png)
### Syntax
There is the following syntax of numpy.sum() function:
numpy.sum(arr, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>) 
  

 




In [12]:
  

#import numpy.array()
import numpy as np  
a=np.array([0.4,0.5])  
b=np.sum(a)  
b  


0.9

In [13]:
import numpy as np  
a=np.array([0.4,0.5,0.9,6.1])  
x=np.sum(a, dtype=np.int32)  
x  

6

# **numpy.zeros() in Python**
The numpy.zeros() function is one of the most significant functions which is used in machine learning programs widely. This function is used to generate an array containing zeros. The numpy.zeros() function provide a new array of given shape and type, which is filled with zeros. 
![image](https://user-images.githubusercontent.com/84801896/123979062-041e6500-d9de-11eb-860a-86ba6ebb55bc.png)

Syntax
numpy.zeros(shape, dtype=float, order='C'  
Parameters
shape: int or tuple of ints

This parameter is used to define the dimensions of the array. This parameter is used for the shape in which we want to create an array, such as (3,2) or 2.

dtype: data-type(optional)

This parameter is used to define the desired data-type for the array. By default, the data-type is numpy.float64. This parameter is not essential for defining.

In [14]:
#numpy.zeros() without dtype and order
import numpy as np  
a=np.zeros(6)  
a  

array([0., 0., 0., 0., 0., 0.])

In [16]:
#numpy.zeros() without order
import numpy as np  
a=np.zeros((6,), dtype=int)  
a   

array([0, 0, 0, 0, 0, 0])

In [17]:
#numpy.zeros() with shape
import numpy as np  
a=np.zeros((6,2))  
a  

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])